# Generated by Django 3.0.2 on 2020-03-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(height_field='800', upload_to='', width_field='640'),
        ),
    ]
